# UpdateApplications.ps1 - Generated by Blackbox.ai

# Update all installed applications
Write-Host "Updating all installed applications..."
winget upgrade --all --silent
if ($LASTEXITCODE -eq 0) {
    Write-Host "All applications updated successfully."
} else {
    Write-Host "Failed to update some applications."
}
