# InstallApplications.ps1 - Generated by Blackbox.ai

# List of applications to install
$applications = @(
    "Google.Chrome",
    "Mozilla.Firefox",
    "Microsoft.VisualStudioCode",
    "Notepad++.Notepad++",
    "7zip.7zip"
)

# Loop through each application and install it
foreach ($app in $applications) {
    Write-Host "Installing $app..."
    winget install --id $app --silent --accept-source-agreements --accept-package-agreements
    if ($LASTEXITCODE -eq 0) {
        Write-Host "$app installed successfully."
    } else {
        Write-Host "Failed to install $app."
    }
}
